### ISSUE TITLE
Feature request: sqlite support

### ISSUE THREAD

**Issue by RouHim** [PhasecoreX/docker-liquidsoap#24]
**Object**
For very large libraries, the liquidsoap docs recommending sqlite for good performance.

**Related docs**
* https://www.liquidsoap.info/doc-dev/database.html
* https://www.liquidsoap.info/doc-dev/cookbook.html#generating-playlists-from-a-media-library

**Implementation**
Just add `sqlite3` to `PACKAGES`.

**My Problem**
Other than reported in my email, I'm now able to use medialib.sqlite (I guess it was a docker cache issue).
I'm still facing some issues, but I believe they are because of my liquidsoap script skill gap.

**Comment by RouHim** [comment]
Review and merge done. Thanks.

**Comment by PhasecoreX** [comment]
Thanks for the pull request, I merged it and it should be ready in an hour or so.
